# Generated by Django 3.2.6 on 2021-10-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_rename_simulatoremails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.PositiveIntegerField(choices=[(0, 'Регистрация'), (1, 'Покупка'), (2, 'Покупка отклонена')], default=0),
        ),
    ]
