# Generated by Django 3.2.10 on 2022-01-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_email_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.PositiveIntegerField(choices=[(0, 'Регистрация'), (1, 'Покупка'), (2, 'Покупка отклонена'), (3, 'Продление подписки')], default=0),
        ),
    ]
