# Generated by Django 3.2.10 on 2022-01-31 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_subscription_vat'),
        ('emails', '0004_alter_email_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription'),
        ),
    ]
