# Generated by Django 3.2.12 on 2022-02-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_alter_email_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.PositiveIntegerField(choices=[(0, 'Регистрация'), (1, 'Покупка'), (2, 'Покупка отклонена'), (3, 'Продление подписки'), (4, 'Отмена подписки'), (5, 'Возобновление подписки'), (6, 'Успешное продление подписки')], default=0),
        ),
    ]
