# Generated by Django 3.2.10 on 2022-01-20 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_groups', '0003_auto_20210909_1016'),
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='simulator_groups.simulatorgroup'),
            preserve_default=False,
        ),
    ]
