# Generated by Django 3.2.16 on 2022-10-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_show_default_courses'),
        ('banners', '0002_banner_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, to='company.Company', verbose_name='Компания'),
        ),
    ]
