# Generated by Django 3.2.10 on 2022-02-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronlog',
            old_name='error_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='cronlog',
            old_name='error_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='cronlog',
            name='is_error',
            field=models.BooleanField(default=True),
        ),
    ]
