# Generated by Django 3.2.12 on 2022-02-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_cron', '0002_remove_max_length_from_CronJobLog_message'),
        ('cron', '0002_auto_20220207_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronlog',
            name='cron',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_cron.cronjoblog'),
            preserve_default=False,
        ),
    ]
