# Generated by Django 3.2.12 on 2022-02-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0003_cronlog_cron'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronlog',
            name='cron',
        ),
    ]
