# Generated by Django 3.2.6 on 2021-09-16 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0011_simulator_show_store'),
        ('payments', '0002_rename_paymentid_payment_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='object_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='simulator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulators.simulator'),
        ),
    ]
