# Generated by Django 3.2.6 on 2021-09-16 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_auto_20210916_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='user_set',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
