# Generated by Django 3.2.6 on 2021-10-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_promocode_user_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='backend',
            field=models.CharField(choices=[('tinkoff', 'Тинькофф'), ('cloudpayments', 'CloudPayments'), ('select', 'Оплата на своем сайте')], max_length=30),
        ),
    ]
