# Generated by Django 3.2.10 on 2022-01-29 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0022_simulator_currency'),
        ('payments', '0005_alter_payment_backend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='is_recurrent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='backend',
            field=models.CharField(choices=[('tinkoff', 'Тинькофф'), ('cloudpayments', 'CloudPayments'), ('select', 'Оплата на своем сайте')], default='tinkoff', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='simulator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulators.simulatoruser'),
        ),
    ]
