# Generated by Django 3.2.16 on 2022-11-13 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0001_initial'),
        ('payments', '0009_payment_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ext_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ext_course.course'),
        ),
    ]
