# Generated by Django 3.2.16 on 2022-11-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_ext_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ext_course',
        ),
    ]
