# Generated by Django 3.2.16 on 2022-11-13 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0007_remove_coursereg_payment'),
        ('payments', '0011_remove_payment_ext_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ext_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ext_course.coursereg'),
        ),
    ]
