# Generated by Django 3.2.17 on 2024-11-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_payment_ext_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
    ]
