# Generated by Django 3.2.6 on 2021-09-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_auto_20210906_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('theory', 'Теория'), ('question', 'Вопрос'), ('message', 'Сообщение'), ('safetext', 'Текст'), ('openquestion', 'Открытый вопрос'), ('test', 'Тест'), ('openquestionexpert', 'Открытый вопрос эксперту'), ('questionanswercheck', 'Открытый вопрос с проверкой'), ('questionuserchoice', 'Вопрос с выбором пользователя')], max_length=200),
        ),
    ]
