# Generated by Django 3.2.3 on 2021-10-10 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0020_placeuser_commented_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeuser',
            name='commented_by_user_set',
            field=models.ManyToManyField(blank=True, related_name='commented_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placeuser',
            name='commented_count',
            field=models.IntegerField(default=0),
        ),
    ]
