# Generated by Django 3.2.8 on 2021-10-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0022_alter_place_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('theory', 'Теория'), ('question', 'Вопрос'), ('message', 'Сообщение'), ('safetext', 'Текст'), ('openquestion', 'Открытый вопрос'), ('test', 'Тест'), ('openquestionexpert', 'Открытый вопрос эксперту'), ('questionanswercheck', 'Открытый вопрос с проверкой'), ('questionuserchoice', 'Вопрос с выбором пользователя'), ('questionrange', 'Открытый вопрос с проверкой значения на интервале'), ('questionexternal', 'Внешний вопрос')], max_length=200),
        ),
    ]
