# Generated by Django 3.2.8 on 2021-10-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0023_alter_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeuser',
            name='admin_comment_requested',
            field=models.BooleanField(default=False),
        ),
    ]
