# Generated by Django 3.2.6 on 2021-12-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0024_placeuser_admin_comment_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='block_complete',
            field=models.BooleanField(default=False),
        ),
    ]
