# Generated by Django 3.2.10 on 2022-01-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0025_place_block_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='need_user',
            field=models.BooleanField(default=False),
        ),
    ]
