# Generated by Django 3.2.13 on 2022-05-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0026_place_need_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='need_payment',
            field=models.BooleanField(default=False),
        ),
    ]
