# Generated by Django 3.2.16 on 2022-11-21 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('theories', '0003_theorychapter_completed_by_user_set'),
        ('places', '0027_place_need_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.character'),
        ),
        migrations.AlterField(
            model_name='place',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='theory_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='theories.theorychapter'),
        ),
    ]
