# Generated by Django 3.2.18 on 2023-04-09 12:25

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0028_auto_20221121_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='auto_answer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='auto_answers',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('theory', 'Теория'), ('question', 'Вопрос'), ('message', 'Сообщение'), ('safetext', 'Текст'), ('openquestion', 'Открытый вопрос'), ('test', 'Тест'), ('openquestionexpert', 'Открытый вопрос эксперту'), ('questionanswercheck', 'Открытый вопрос с проверкой'), ('questionuserchoice', 'Вопрос с выбором пользователя'), ('questionrange', 'Открытый вопрос с проверкой значения на интервале'), ('questionexternal', 'Внешний вопрос'), ('aiopenquestion', 'Вопрос с нейронками')], max_length=200),
        ),
    ]
