# Generated by Django 3.2.17 on 2023-04-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0029_auto_20230409_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
