# Generated by Django 3.2.18 on 2023-04-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0030_place_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='gpt_generate',
            field=models.BooleanField(default=False),
        ),
    ]
