# Generated by Django 3.2.18 on 2023-04-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0031_place_gpt_generate'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='preprompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
