# Generated by Django 3.2.17 on 2023-08-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0032_place_preprompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('theory', 'Теория'), ('question', 'Вопрос'), ('message', 'Сообщение'), ('safetext', 'Текст'), ('openquestion', 'Открытый вопрос'), ('test', 'Тест'), ('openquestionexpert', 'Открытый вопрос эксперту'), ('questionanswercheck', 'Открытый вопрос с проверкой'), ('questionuserchoice', 'Вопрос с выбором пользователя'), ('questionrange', 'Открытый вопрос с проверкой значения на интервале'), ('questionexternal', 'Внешний вопрос'), ('aiopenquestion', 'Вопрос с нейронками'), ('testaiopenquestion', 'Тестовый вопрос с нейронками')], max_length=200),
        ),
    ]
