# Generated by Django 3.2.14 on 2022-10-07 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulators', '0025_rename_is_paid_simulatoruser_simulator_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False, verbose_name='Активно, если нет, то будет стоять ссылка на занятие')),
                ('link', models.TextField(blank=True, null=True)),
                ('top_part', models.TextField(verbose_name='Обычно, место для видеозаписи')),
                ('bot_part', models.TextField(verbose_name='Обычно, место для домашних работ и прочей информации')),
                ('simulators', models.ManyToManyField(related_name='lessons_simulators', to='simulators.Simulator')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('sub_name', models.CharField(max_length=255, verbose_name='название серым (например, обозначить поток + подписку)')),
                ('show_front', models.BooleanField(default=False)),
                ('link', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='course')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='slug')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
