# Generated by Django 3.2.14 on 2022-10-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_auto_20220124_2349'),
        ('course', '0002_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='simulators',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lessons',
            field=models.ManyToManyField(related_name='lessons_Course', to='lessons.Lesson'),
        ),
    ]
