# Generated by Django 3.2.14 on 2022-10-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='current',
            field=models.IntegerField(default=1),
        ),
    ]
