# Generated by Django 3.2.14 on 2022-10-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='bot_part',
            field=models.TextField(blank=True, verbose_name='Обычно, место для домашних работ и прочей информации'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='top_part',
            field=models.TextField(blank=True, verbose_name='Обычно, место для видеозаписи'),
        ),
    ]
