# Generated by Django 3.2.14 on 2022-10-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20221011_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='inactive_text',
            field=models.TextField(blank=True, verbose_name='Текст, если ссылка на занятие'),
        ),
    ]
