# Generated by Django 3.2.16 on 2022-10-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_auto_20220124_2349'),
        ('course', '0008_alter_lesson_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lessons',
            field=models.ManyToManyField(related_name='lessons_Course', to='lessons.Lesson'),
        ),
    ]
