# Generated by Django 3.2.16 on 2022-10-19 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_lesson_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lessons',
        ),
    ]
