# Generated by Django 3.2.16 on 2022-10-19 23:47

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_auto_20220124_2349'),
        ('course', '0011_remove_lesson_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lessons',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='lessons_Course', to='lessons.Lesson'),
        ),
    ]
