# Generated by Django 3.2.16 on 2022-10-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_show_default_courses'),
        ('course', '0013_course_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='company',
        ),
        migrations.AddField(
            model_name='course',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, to='company.Company', verbose_name='Компания'),
        ),
    ]
