# Generated by Django 3.2.17 on 2023-04-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20221031_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_next',
            field=models.BooleanField(default=False),
        ),
    ]
