# Generated by Django 3.2.17 on 2023-04-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20230428_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='badge_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
