# Generated by Django 3.2.16 on 2022-12-10 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('phrase', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackSituationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('structure', models.TextField(blank=True, null=True)),
                ('marks', models.IntegerField(default=0)),
                ('my_count_marks', models.IntegerField(default=0)),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbacksituation', verbose_name='Ситуация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackSituationUserMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_id', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('s_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbacksituationuser', verbose_name='Пользователь')),
            ],
        ),
    ]
