# Generated by Django 3.2.16 on 2022-12-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksituationuser',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
