# Generated by Django 3.2.16 on 2022-12-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbacksituationuser_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacksituationusermark',
            old_name='mark_id',
            new_name='mark',
        ),
    ]
