# Generated by Django 3.2.16 on 2023-02-02 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0003_rename_mark_id_feedbacksituationusermark_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=feedback.models.rand_slug, max_length=10, unique=True)),
                ('is_started', models.BooleanField(default=False)),
                ('is_end', models.BooleanField(default=False)),
                ('round', models.IntegerField(default=0)),
                ('situation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.IntegerField()),
                ('structure', models.TextField(blank=True)),
                ('cards_sends', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gameuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card1', models.CharField(blank=True, max_length=100)),
                ('card2', models.CharField(blank=True, max_length=100)),
                ('card3', models.CharField(blank=True, max_length=100)),
                ('lifes', models.IntegerField(default=3)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameRoundCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.TextField()),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.gameround')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.gameuser')),
            ],
        ),
    ]
