# Generated by Django 3.2.17 on 2023-04-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_userpageprogress_next_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpageprogress',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
