# Generated by Django 3.2.8 on 2021-10-17 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0023_alter_place_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('commented', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.placeuser')),
            ],
        ),
    ]
