# Generated by Django 3.2.8 on 2021-10-19 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0024_placeuser_admin_comment_requested'),
        ('comment_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrequest',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.placeuser'),
        ),
    ]
