# Generated by Django 3.2.8 on 2021-10-21 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0024_placeuser_admin_comment_requested'),
        ('comment_requests', '0002_alter_commentrequest_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentrequest',
            name='answer',
        ),
        migrations.AddField(
            model_name='commentrequest',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.place'),
        ),
    ]
