# Generated by Django 3.2.12 on 2022-03-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Фамилия Имя')),
                ('img', models.ImageField(blank=True, null=True, upload_to='teachers')),
                ('description', models.TextField(blank=True, null=True)),
                ('tag', models.ManyToManyField(blank=True, to='teachers.Tags')),
            ],
        ),
    ]
