# Generated by Django 3.2.12 on 2022-03-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
