# Generated by Django 3.2.12 on 2022-03-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='slug',
        ),
    ]
