# Generated by Django 3.2.12 on 2022-03-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_remove_teacher_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
