# Generated by Django 3.2.12 on 2022-03-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teacher_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='from_teacher',
            field=models.TextField(blank=True, null=True, verbose_name='Описание словами учителя'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='heading',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Жирное описание'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='small_description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Маленькое описание (не более 100 символов без html)'),
        ),
    ]
