# Generated by Django 3.2.12 on 2022-04-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20220323_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок вывода. Чем больше, тем первее'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='heading',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Жирное описание'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='small_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Маленькое описание (не более 200 символов без html)'),
        ),
    ]
