# Generated by Django 3.2.13 on 2022-05-30 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('chat_id', models.BigIntegerField()),
                ('command', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userDecoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('countMarkSituation', models.IntegerField(default=0)),
                ('lastSituation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='decoding.situation', verbose_name='Ситуация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='SituationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('marks', models.IntegerField(default=0)),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decoding.situation', verbose_name='Ситуация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decoding.userdecoding', verbose_name='Пользователь')),
            ],
        ),
    ]
