# Generated by Django 3.2.13 on 2022-05-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='active',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='command',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='value',
        ),
        migrations.AddField(
            model_name='situation',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='situation',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
