# Generated by Django 3.2.13 on 2022-05-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoding', '0002_auto_20220530_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='phrase',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='situation',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
