# Generated by Django 3.2.13 on 2022-05-31 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decoding', '0003_auto_20220531_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdecoding',
            name='countMarkSituation',
        ),
        migrations.RemoveField(
            model_name='userdecoding',
            name='lastSituation',
        ),
        migrations.AlterField(
            model_name='situationuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
