# Generated by Django 3.2.13 on 2022-05-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoding', '0004_auto_20220531_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='situationuser',
            name='my_count_marks',
            field=models.IntegerField(default=0),
        ),
    ]
