# Generated by Django 3.2.10 on 2022-01-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_groups', '0003_auto_20210909_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatorgroup',
            name='pay_EmailCompany',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulatorgroup',
            name='pay_TerminalKey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulatorgroup',
            name='pay_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulatorgroup',
            name='pay_type',
            field=models.CharField(choices=[('tinkoff', 'Тинькофф'), ('cloudpayments', 'CloudPayments'), ('select', 'Оплата на своем сайте')], default='tinkoff', max_length=255),
        ),
        migrations.AddField(
            model_name='simulatorgroup',
            name='pay_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulatorgroup',
            name='vat',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
