# Generated by Django 3.2.10 on 2022-01-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_groups', '0005_auto_20220129_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulatorgroup',
            name='vat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
