# Generated by Django 3.2.12 on 2022-02-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
    ]
