# Generated by Django 3.2.12 on 2022-02-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_tag_is_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
