# Generated by Django 3.2.13 on 2022-05-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='command',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
