# Generated by Django 3.2.13 on 2022-05-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20220503_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='command',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
