# Generated by Django 3.2.17 on 2024-01-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20220503_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
