# Generated by Django 3.2.14 on 2022-07-31 22:42

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='tests', verbose_name='Иконка')),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='tests', verbose_name='Картинка')),
                ('slug', models.CharField(max_length=255, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='CategorySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='tests', verbose_name='Картинка')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test.category')),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя тестируемого')),
                ('tester', models.CharField(max_length=255, verbose_name='Тестирующий')),
                ('version', models.IntegerField(default=1)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('books', models.TextField()),
                ('simulators', models.TextField()),
                ('excercises', models.TextField()),
                ('more', models.TextField()),
                ('slug', models.CharField(max_length=255, verbose_name='slug')),
                ('categories', models.ManyToManyField(through='test.CategorySkill', to='test.Category')),
            ],
        ),
        migrations.AddField(
            model_name='categoryskill',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test.skill'),
        ),
    ]
