# Generated by Django 3.2.14 on 2022-08-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='books',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='excercises',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='more',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='simulators',
            field=models.TextField(blank=True),
        ),
    ]
