# Generated by Django 3.2.14 on 2022-08-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_result_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='slug',
            field=models.CharField(blank=True, max_length=255, verbose_name='slug'),
        ),
    ]
