# Generated by Django 3.2.14 on 2025-10-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0005_context_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="books",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="excercises",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="more",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
