# Generated by Django 3.2.10 on 2022-01-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_usersubscription_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='type',
            field=models.IntegerField(choices=[(0, 'Нет подписки'), (1, 'Заполнен профиль'), (2, 'Базовая подписка'), (3, 'Платная подписка')], default=0),
        ),
    ]
