# Generated by Django 3.2.10 on 2022-01-23 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_lesson_full_info'),
        ('subscriptions', '0004_alter_usersubscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='include_subscriptions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='lessons.Lesson'),
        ),
    ]
