# Generated by Django 3.2.10 on 2022-01-24 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20220123_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='include_subscriptions',
        ),
    ]
