# Generated by Django 3.2.10 on 2022-01-24 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_remove_subscription_include_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='lessons',
        ),
    ]
