# Generated by Django 3.2.10 on 2022-01-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_auto_20220128_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='period',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='trial_expired',
            field=models.BooleanField(default=False),
        ),
    ]
