# Generated by Django 3.2.10 on 2022-01-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_auto_20220129_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='vat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
