# Generated by Django 3.2.10 on 2022-02-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_subscription_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='trial_period',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='period',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
