# Generated by Django 3.2.10 on 2022-02-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_auto_20220201_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='type',
            field=models.IntegerField(choices=[(0, 'Нет подписки'), (1, 'Заполнен профиль'), (2, 'Базовая подписка'), (3, 'Пробный период'), (4, 'Платная подписка')], default=0),
        ),
    ]
