# Generated by Django 3.2.10 on 2022-02-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_alter_usersubscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='alert',
            field=models.BooleanField(default=False),
        ),
    ]
