# Generated by Django 3.2.10 on 2022-02-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_usersubscription_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='type',
            field=models.IntegerField(choices=[(0, 'Нет подписки'), (1, 'Заполнен профиль'), (2, 'Базовая подписка'), (3, 'Попытка оплаты пробной подписки'), (4, 'Попытка оплаты полной подписки'), (5, 'Пробный период'), (6, 'Платная подписка')], default=0),
        ),
    ]
