# Generated by Django 3.2.12 on 2022-04-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_alter_usersubscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_club',
            field=models.BooleanField(default=False),
        ),
    ]
