# Generated by Django 3.2.14 on 2022-10-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_subscription_is_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='resubscribe_try',
            field=models.BooleanField(default=False),
        ),
    ]
