# Generated by Django 3.2.16 on 2022-10-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='show_default_nav',
            field=models.BooleanField(default=True),
        ),
    ]
