# Generated by Django 3.2.16 on 2022-10-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_show_default_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='show_default_courses',
            field=models.BooleanField(default=True),
        ),
    ]
