# Generated by Django 3.2.17 on 2023-06-04 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0025_rename_is_paid_simulatoruser_simulator_paid'),
        ('company', '0003_company_show_default_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_simulator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulators.simulator'),
        ),
    ]
