# Generated by Django 3.2.17 on 2023-09-07 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_custom_simulator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemails',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
