# Generated by Django 3.2.10 on 2021-12-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_userdayhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='user_avatars/default_avatar.jpg', null=True, upload_to='user_avatars'),
        ),
    ]
