# Generated by Django 3.2.10 on 2022-01-09 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20220109_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
