# Generated by Django 3.2.10 on 2022-01-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20220109_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='user_avatars/default_avatar.png', null=True, upload_to='user_avatars'),
        ),
    ]
