# Generated by Django 3.2.12 on 2022-03-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club',
            field=models.TextField(blank=True, null=True),
        ),
    ]
