# Generated by Django 3.2.12 on 2022-04-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='user',
            name='rating_fast',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='user',
            name='rating_text_game',
            field=models.IntegerField(default=1200),
        ),
    ]
