# Generated by Django 3.2.12 on 2022-04-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_alter_user_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='club',
            field=models.TextField(blank=True, null=True),
        ),
    ]
