# Generated by Django 3.2.12 on 2022-04-27 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20220427_1627'),
        ('user_profile', '0016_alter_user_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club', verbose_name='Клуб человека'),
        ),
    ]
