# Generated by Django 3.2.12 on 2022-04-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0017_user_club_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='club',
        ),
    ]
