# Generated by Django 3.2.12 on 2022-04-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_auto_20220427_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='playerClub',
        ),
    ]
