# Generated by Django 3.2.12 on 2022-04-27 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20220427_1627'),
        ('user_profile', '0020_remove_user_playerclub'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clubs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.club', verbose_name='Клуб'),
        ),
    ]
