# Generated by Django 3.2.12 on 2022-04-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0021_user_clubs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clubs',
        ),
    ]
