# Generated by Django 3.2.12 on 2022-04-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_club_field'),
        ('user_profile', '0022_remove_user_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.club', verbose_name='Клуб'),
        ),
    ]
