# Generated by Django 3.2.14 on 2022-09-19 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_auto_20220124_2349'),
        ('user_profile', '0023_user_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.lesson'),
        ),
    ]
