# Generated by Django 3.2.14 on 2022-10-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0024_alter_user_last_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe_try',
            field=models.BooleanField(default=False),
        ),
    ]
