# Generated by Django 3.2.14 on 2022-10-14 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0025_user_subscribe_try'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribe_try',
        ),
    ]
