# Generated by Django 3.2.16 on 2022-10-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0027_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_admin',
            field=models.BooleanField(default=False),
        ),
    ]
