# Generated by Django 3.2.16 on 2022-12-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0028_user_company_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_trainer_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_trainer_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
