# Generated by Django 3.2.17 on 2024-02-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0029_auto_20221229_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating_tournament',
            field=models.IntegerField(default=0),
        ),
    ]
