# Generated by Django 3.2.8 on 2021-10-17 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theories', '0002_alter_theorychapter_sequence_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorychapter',
            name='completed_by_user_set',
            field=models.ManyToManyField(blank=True, related_name='completed_theroies', to=settings.AUTH_USER_MODEL),
        ),
    ]
