# Generated by Django 3.2.3 on 2021-09-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0010_simulator_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='show_store',
            field=models.BooleanField(default=False),
        ),
    ]
