# Generated by Django 3.2.8 on 2021-10-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0011_simulator_show_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatoruser',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
