# Generated by Django 3.2.8 on 2021-10-19 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0012_simulatoruser_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulatoruser',
            name='score',
        ),
    ]
