# Generated by Django 3.2.6 on 2021-10-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0013_remove_simulatoruser_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulator',
            name='pay_type',
            field=models.CharField(choices=[('tinkoff', 'Тинькофф'), ('cloudpayments', 'CloudPayments'), ('select', 'Оплата на своем сайте')], default='tinkoff', max_length=255),
        ),
    ]
