# Generated by Django 3.2.6 on 2021-10-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0014_alter_simulator_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='pay_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
