# Generated by Django 3.2.6 on 2021-10-25 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0015_simulator_pay_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulator',
            name='css',
            field=models.FileField(blank=True, null=True, upload_to='simulator_css', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['css'])]),
        ),
    ]
