# Generated by Django 3.2.6 on 2021-12-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0017_auto_20211214_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='buy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='makeuser_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='need_buy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
