# Generated by Django 3.2.6 on 2021-12-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0019_auto_20211214_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='author_comment_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='bought_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='have_promo_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='price_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='promocode_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
