# Generated by Django 3.2.6 on 2021-12-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0020_auto_20211214_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='send_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
