# Generated by Django 3.2.10 on 2022-01-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0021_simulator_send_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
