# Generated by Django 3.2.10 on 2022-01-29 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0022_simulator_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulator',
            old_name='pay_EmailCompany',
            new_name='pay_email_company',
        ),
        migrations.RenameField(
            model_name='simulator',
            old_name='pay_TerminalKey',
            new_name='pay_terminal_key',
        ),
    ]
