# Generated by Django 3.2.10 on 2022-01-29 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0023_auto_20220129_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulatoruser',
            old_name='simulator_paid',
            new_name='is_paid',
        ),
    ]
