# Generated by Django 3.2.10 on 2022-01-29 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0024_rename_simulator_paid_simulatoruser_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulatoruser',
            old_name='is_paid',
            new_name='simulator_paid',
        ),
    ]
