# Generated by Django 3.2.16 on 2022-11-13 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0002_coursereg_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursereg',
            old_name='Course',
            new_name='сourse',
        ),
        migrations.CreateModel(
            name='CoursePromocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Промокод')),
                ('price', models.FloatField()),
                ('сourse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ext_course.course')),
            ],
        ),
    ]
