# Generated by Django 3.2.16 on 2022-11-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0003_auto_20221113_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='theme',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тема'),
        ),
    ]
