# Generated by Django 3.2.16 on 2022-11-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0004_auto_20221113_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereg',
            name='final_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursereg',
            name='promocode',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
