# Generated by Django 3.2.16 on 2022-11-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0005_auto_20221113_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereg',
            name='additional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
