# Generated by Django 3.2.16 on 2022-11-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0006_alter_coursereg_additional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereg',
            name='payment',
        ),
    ]
