# Generated by Django 3.2.16 on 2022-11-13 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_groups', '0006_alter_simulatorgroup_vat'),
        ('ext_course', '0007_remove_coursereg_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulator_groups.simulatorgroup'),
        ),
    ]
