# Generated by Django 3.2.16 on 2022-11-13 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0008_course_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursereg',
            old_name='сourse',
            new_name='course',
        ),
    ]
