# Generated by Django 3.2.16 on 2022-11-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0009_rename_сourse_coursereg_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursepromocode',
            old_name='сourse',
            new_name='course',
        ),
    ]
