# Generated by Django 3.2.16 on 2022-11-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0010_rename_сourse_coursepromocode_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='telegram',
            field=models.TextField(blank=True),
        ),
    ]
