# Generated by Django 3.2.16 on 2022-11-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0011_course_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereg',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
