# Generated by Django 3.2.16 on 2022-12-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0012_coursereg_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh', models.TextField(blank=True, null=True)),
                ('expires', models.DateTimeField(auto_now_add=True)),
                ('refresh_time', models.IntegerField(default=86400)),
                ('access', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
