# Generated by Django 3.2.16 on 2022-12-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0013_amodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereg',
            name='pipe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursereg',
            name='to_amo',
            field=models.BooleanField(default=False),
        ),
    ]
