# Generated by Django 3.2.16 on 2022-12-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0014_auto_20221221_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereg',
            name='in_amo',
            field=models.BooleanField(default=False),
        ),
    ]
