# Generated by Django 3.2.16 on 2022-12-21 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0015_coursereg_in_amo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereg',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
