# Generated by Django 3.2.16 on 2022-12-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0016_coursereg_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereg',
            name='to_amo',
            field=models.BooleanField(default=True),
        ),
    ]
