# Generated by Django 3.2.16 on 2022-12-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0017_alter_coursereg_to_amo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amo_pipe',
            field=models.TextField(blank=True),
        ),
    ]
