# Generated by Django 3.2.16 on 2022-12-21 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0018_course_amo_pipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereg',
            name='pipe',
        ),
    ]
