# Generated by Django 3.2.16 on 2022-12-21 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0019_remove_coursereg_pipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='amo_pipe',
        ),
    ]
