# Generated by Django 3.2.16 on 2022-12-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0020_remove_course_amo_pipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amo_pipe',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
