# Generated by Django 3.2.16 on 2022-12-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0022_alter_course_amo_pipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereg',
            name='amo_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
