# Generated by Django 3.2.16 on 2022-12-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0023_coursereg_amo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amo_paid_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
