# Generated by Django 3.2.17 on 2024-04-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_course', '0024_course_amo_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereg',
            name='utm_campaign',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursereg',
            name='utm_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursereg',
            name='utm_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursereg',
            name='utm_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursereg',
            name='utm_term',
            field=models.TextField(blank=True, null=True),
        ),
    ]
