# Generated by Django 3.2.12 on 2022-04-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club',
        ),
    ]
