# Generated by Django 3.2.12 on 2022-04-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
