# Generated by Django 3.2.12 on 2022-04-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20220427_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('schedule', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Clubs',
        ),
    ]
