# Generated by Django 3.2.12 on 2022-04-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0022_remove_user_clubs'),
        ('club', '0005_auto_20220427_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club',
        ),
    ]
