# Generated by Django 3.2.12 on 2022-04-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='field',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
