# Generated by Django 3.2.12 on 2022-04-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_club_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='field',
        ),
    ]
