# Generated by Django 3.2.12 on 2022-04-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_remove_club_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='clubs'),
        ),
    ]
