# Generated by Django 3.2.12 on 2022-04-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.IntegerField(choices=[(0, 'Конфликты'), (1, 'Переговоры')], default=0, verbose_name='тип'),
            preserve_default=False,
        ),
    ]
