# Generated by Django 3.2.12 on 2022-04-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_game_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='clubs')),
                ('order', models.IntegerField(verbose_name='порядок вывода. Чем больше тем раньше')),
            ],
        ),
    ]
