# Generated by Django 3.2.17 on 2024-02-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0015_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
