# Generated by Django 3.2.17 on 2024-02-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0016_club_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('schedule', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=50)),
                ('show', models.BooleanField(default=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='clubs')),
            ],
        ),
    ]
