# Generated by Django 3.2.17 on 2024-02-04 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0017_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='place1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='место 1'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='place2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place2', to=settings.AUTH_USER_MODEL, verbose_name='место 2'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='place3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place3', to=settings.AUTH_USER_MODEL, verbose_name='место 3'),
        ),
    ]
