# Generated by Django 3.2.14 on 2022-09-04 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='botUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('command', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(max_length=255, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='botUserSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, verbose_name='slug')),
                ('finished', models.BooleanField(default=False)),
                ('page', models.IntegerField(default=1)),
                ('bot_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.botuser')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[('Plus', 1), ('Minus', -1)], default=-1)),
                ('default_answers', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('max_points', models.IntegerField(default=100)),
                ('min_points', models.IntegerField(default=0)),
                ('bad_points', models.IntegerField(default=0)),
                ('normal_points', models.IntegerField(default=0)),
                ('good_points', models.IntegerField(default=0)),
                ('bad_comment', models.TextField(blank=True)),
                ('normal_comment', models.TextField(blank=True)),
                ('good_comment', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.category')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.IntegerField(choices=[('самого пользователя', 0), ('друзья и родственники', 1), ('Работа', 1)], default=0)),
                ('slug', models.CharField(max_length=255, verbose_name='slug')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Survey_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('page', models.IntegerField(default=1)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.question')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.survey')),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(through='poll.Survey_Question', to='poll.Question'),
        ),
        migrations.AddField(
            model_name='survey',
            name='results',
            field=models.ManyToManyField(to='poll.Result'),
        ),
        migrations.AddField(
            model_name='question',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.result'),
        ),
        migrations.CreateModel(
            name='botUserSurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(default=0)),
                ('bot_user_survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.botusersurvey')),
            ],
        ),
        migrations.CreateModel(
            name='botUserSurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='slug')),
                ('bot_user_survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.botusersurvey')),
            ],
        ),
        migrations.AddField(
            model_name='botusersurvey',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.survey'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('value', models.IntegerField(default=1)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.question')),
            ],
        ),
    ]
