# Generated by Django 3.2.14 on 2022-09-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, 'Plus'), (-1, 'Minus')], default=-1),
        ),
        migrations.AlterField(
            model_name='survey',
            name='category',
            field=models.IntegerField(choices=[(0, 'самого пользователя'), (1, 'друзья и родственники'), (2, 'Работа')], default=0),
        ),
        migrations.AlterField(
            model_name='survey',
            name='results',
            field=models.ManyToManyField(blank=True, to='poll.Result'),
        ),
    ]
