# Generated by Django 3.2.14 on 2022-09-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20220908_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='age',
            field=models.IntegerField(blank=True, choices=[(0, 'Меньше 18'), (1, '18-24'), (2, '25-34'), (3, '35-45'), (4, 'больше 45')], null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='company_slug',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'W'), (1, 'M')], null=True),
        ),
    ]
