# Generated by Django 3.2.14 on 2022-09-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20220912_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='company_slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
