# Generated by Django 3.2.14 on 2022-09-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_botuser_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
