# Generated by Django 3.2.14 on 2022-09-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_survey_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='result',
        ),
        migrations.AddField(
            model_name='question',
            name='result',
            field=models.ManyToManyField(blank=True, null=True, to='poll.Result'),
        ),
    ]
