# Generated by Django 3.2.8 on 2021-10-17 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0023_alter_place_type'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='comment',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='notification',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.placeuser'),
        ),
    ]
