# Generated by Django 3.2.8 on 2021-10-19 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment_requests', '0002_alter_commentrequest_answer'),
        ('notifications', '0002_auto_20211017_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment_requests.commentrequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('user_comment', 'Комментарий пользователя'), ('admin_comment', 'Комментарий админа')], default='user_comment', max_length=200),
        ),
    ]
