# Generated by Django 3.2.6 on 2021-10-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_lesson_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
