# Generated by Django 3.2.10 on 2022-01-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_alter_lesson_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
