# Generated by Django 3.2.10 on 2022-01-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_lesson_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='full_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
