# Generated by Django 3.2.10 on 2022-01-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_lesson_full_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='amount_places_without_subscription',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='need_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
