# Generated by Django 3.2.17 on 2023-08-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_auto_20220124_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
