# Generated by Django 3.2.17 on 2023-08-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_lesson_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='test_key',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
