# Generated by Django 3.2.10 on 2022-01-25 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulator_groups', '0003_auto_20210909_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recommendations_images')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator_groups.simulatorgroup')),
            ],
        ),
    ]
