# Generated by Django 3.2.10 on 2022-01-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_auto_20220124_2349'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='lessons.Lesson'),
        ),
    ]
